apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer # External service to communicate with client
  selector:
    app: gateway
  ports:
  - port: 80 #port of service
    targetPort: 9696 #port of load balancer
