apiVersion: v1
kind: Service
metadata:
  name: tf-serving-flower-model
spec:
  type: ClusterIP #default service is ClusterIP (which is an internal service)
  selector:
    app: tf-serving-flower-model
  ports:
  - port: 8500
    targetPort: 8500
